let sample_num = 0;
console.log(sample_num);
sample_num += 100;
console.log(sample_num);
sample_num -= 50;
console.log(sample_num);
sample_num *= 2;
console.log(sample_num);
sample_num /= 5;
console.log(sample_num);
sample_num **= 2;
console.log(sample_num);
sample_num %= 3;
console.log(sample_num);
